# This is a basic workflow to help you get started with Actions

name: AWSDeployment

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: Run a multi-line script
        run: |
          echo ${{ secrets.AWS_ACCESS_KEY_ID }}
          echo test, and deploy your project.

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      # Runs a set of commands using the runners shell

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18  # Use a versão apropriada para seu projeto

      - name: Install dependencies and build
        run: |
          npm ci
          npm run build
          
     
